name: "Digger's Den"
description: "The Blog for Brian Hess"

url: "https://brianmhess.github.io"

paginate: 10

markdown: kramdown
kramdown:
  input: "GFM"
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge
permalink: pretty
#pygments: true

gems: [jekyll-paginate, kramdown, rouge, jekyll-feed]
